### ISSUE TITLE
Remove "using namespace" from header file

### ISSUE THREAD

**Issue by HPDell** [GWmodel-Lab/libgwmodel#17]

**Comment by Tejas021** [comment]
I want to work on this issue
Can you elaborate ant further

**Comment by HPDell** [comment]
> I want to work on this issue Can you elaborate a little further

Sorry for replying so late. I read *Effectiveness Modern C++* or a post where the author mentioned that never write `using namespace std` in headers or it could cause some unexpected bugs when using this library. So I published this issue about removing all `using namespace` (not only `std` but also `arma`). Currently, `using namespace std` appears in many header files.

I felt so happy to hear that you discovered this library and wanted to make some contribution. If you are still keen on fixing this problem, I appreciate it very much.
