### ISSUE TITLE
GTWR

### ISSUE THREAD

**Issue by HPDell** [GWmodel-Lab/libgwmodel#8]

**Comment by HPDell** [comment]
- [ ] 需要增加 lambda 值优选的功能

**Comment by HPDell** [comment]
做了以下更改，你之前说的问题应该被绕过去了

1. 新的 `CRSSTDistance` 由一个 `Distance` 和一个 `OneDimDistance` 组合而来，前者表示空间距离，后者表示时间距离。前者可以是任意类型的距离，后者表示一个时间。
2. 时空距离计算的函数改成了先计算空间距离，再计算时间距离，再计算时空距离，使用的是参数 lambda 和一个角度 angle。这个 angle 默认是 pi/2 ，即正交。
3. 当正交的时候，调用计算正交时空距离的函数，否则调用斜交时空距离的函数。

之所以要这样更改，是因为时空距离并不一定要限定空间距离是直线距离，理应可以是任何一种距离。之前从 `CRSDistance` 派生子类的做法不能覆盖全部逻辑。

下面需要有几点对代码进行完善：

- [ ] 基于现在的设计完成 GTWR 的编写。
- [ ] 检查在创建 `CRSSTDistance` 对象时，其类型为 `Distance` 基类的空间距离对象，不能是 `CRSSTDistance` 本身。
- [ ] GTWR 在设置 `mSpatialWeights` 时要检查传入对象的距离部分是不是 `CRSSTDistance` 类型。

代码 rebase 到了最新的 master 上，你如果要更新的话需要这样

```bash
git pull --rebase -f
```

**Comment by GRoryu** [comment]
lambda 值优选功能未实现，如何实现？
lambda≠1的计算结果依旧和R包有一点差距，原因可能是R包计算时间距离时将负值赋0
lambda=1即回归到GWR basic的结果测试通过
带宽优选方面情况同上。

**Comment by HPDell** [comment]
负时间距离时权重设置为0的处理应该已经在2.9版本的GWmodel中移除了，不行更新下版本试试。

**Comment by GRoryu** [comment]
另外，在merge的时候不小心忽略了头文件引用的修改，顺便改掉了openmp里面int和uword的for循环设置（改成了和其它函数一样的写法）导致多了一个commit 3151b135fd3a372b52de5711cb20c662d5b4ade8
